# Regression Models with Keras

## Introduction
Despite the popularity of more powerful libraries such as PyToch and TensorFlow, they are not easy to use and have a steep learning curve. So, for people who are just starting to learn deep learning, there is no better library to use other than the Keras library. 

Keras is a high-level API for building deep learning models. It has gained favor for its ease of use and syntactic simplicity facilitating fast development. As you will see in this lab and the other labs in this course, building a very complex deep learning network can be achieved with Keras with only few lines of code. You will appreciate Keras even more, once you learn how to build deep models using PyTorch and TensorFlow in the other courses.


## Objectives for this Notebook    
* How to use the Keras library to build a regression model
* Download and clean the data set
* Build a neural network
* Train and test the network

#### Import Dataset

In [7]:
import numpy as np
import keras
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests

In [8]:
def download(url,fileName):
    response = requests.get(url)
    if(response.status_code == 200 ):
        with open(fileName, "wb") as f:
            f.write(response.content)

In [10]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
file_name = 'concrete_data.csv'
download(filepath,file_name)

In [11]:
df = pd.read_csv(file_name)
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [12]:
# check how many data we have
df.shape

(1030, 9)

In [13]:
#check missing values
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [14]:
df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

#### Split data into predictors and target

In [28]:
#predictors will be the all the columns except the concreate strength


predictors = df.drop(columns={'Strength'})
target = df['Strength']
predictors_columns = predictors.columns

In [25]:
print("predictors:\n", predictors.head())
print("\ntarget:\n", target.head())

predictors:
    Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
0   540.0                 0.0      0.0  162.0               2.5
1   540.0                 0.0      0.0  162.0               2.5
2   332.5               142.5      0.0  228.0               0.0
3   332.5               142.5      0.0  228.0               0.0
4   198.6               132.4      0.0  192.0               0.0

   Coarse Aggregate  Fine Aggregate  Age
0            1040.0           676.0   28
1            1055.0           676.0   28
2             932.0           594.0  270
3             932.0           594.0  365
4             978.4           825.5  360

target:
 0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

#### Standardization the Data

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
predictors_scaled = pd.DataFrame(scaler.fit_transform(predictors),columns=predictors_columns)

print("Scaled predictors:\n", predictors_scaled.head())

Scaled predictors:
      Cement  Blast Furnace Slag   Fly Ash     Water  Superplasticizer  \
0  2.477915           -0.856888 -0.847144 -0.916764         -0.620448
1  2.477915           -0.856888 -0.847144 -0.916764         -0.620448
2  0.491425            0.795526 -0.847144  2.175461         -1.039143
3  0.491425            0.795526 -0.847144  2.175461         -1.039143
4 -0.790459            0.678408 -0.847144  0.488793         -1.039143

   Coarse Aggregate  Fine Aggregate       Age
0          0.863154       -1.217670 -0.279733
1          1.056164       -1.217670 -0.279733
2         -0.526517       -2.240917  3.553066
3         -0.526517       -2.240917  5.057677
4          0.070527        0.647884  4.978487

In [42]:
# number of columns
n_cols = predictors_scaled.shape[1]
n_cols

8

### Import Keras Package

In [43]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

### Build Neural Network

In [46]:
def regression_model():
    
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50,activation='relu'))
    model.add(Dense(50,activation='relu'))
    model.add(Dense(1))
    
    #compile the model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

## Train and Test the Network

In [47]:
#Build the model
model = regression_model()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Next, we will train and test the model at the same time using the *fit* method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.

In [48]:
model.fit(predictors_scaled,target,validation_split=0.3,epochs=100, verbose=2)

Epoch 1/100
23/23 - 2s - 68ms/step - loss: 1668.3635 - val_loss: 1152.5658
Epoch 2/100
23/23 - 0s - 6ms/step - loss: 1537.0236 - val_loss: 1035.2765
Epoch 3/100
23/23 - 0s - 6ms/step - loss: 1337.2964 - val_loss: 862.5869
Epoch 4/100
23/23 - 0s - 6ms/step - loss: 1040.8108 - val_loss: 638.7996
Epoch 5/100
23/23 - 0s - 5ms/step - loss: 686.5903 - val_loss: 414.0443
Epoch 6/100
23/23 - 0s - 5ms/step - loss: 400.3535 - val_loss: 254.0700
Epoch 7/100
23/23 - 0s - 5ms/step - loss: 263.7910 - val_loss: 187.1994
Epoch 8/100
23/23 - 0s - 8ms/step - loss: 224.1950 - val_loss: 167.7390
Epoch 9/100
23/23 - 0s - 7ms/step - loss: 208.9272 - val_loss: 159.8141
Epoch 10/100
23/23 - 0s - 8ms/step - loss: 199.9518 - val_loss: 158.3642
Epoch 11/100
23/23 - 0s - 7ms/step - loss: 193.3493 - val_loss: 157.3512
Epoch 12/100
23/23 - 0s - 5ms/step - loss: 187.2962 - val_loss: 156.0791
Epoch 13/100
23/23 - 0s - 6ms/step - loss: 182.2327 - val_loss: 153.1874
Epoch 14/100
23/23 - 0s - 6ms/step - loss: 178.9400 - val_loss: 151.9777
Epoch 15/100
23/23 - 0s - 6ms/step - loss: 174.8125 - val_loss: 150.3646
Epoch 16/100
23/23 - 0s - 7ms/step - loss: 171.2686 - val_loss: 151.9524
Epoch 17/100
23/23 - 0s - 6ms/step - loss: 168.1179 - val_loss: 147.6660
Epoch 18/100
23/23 - 0s - 6ms/step - loss: 165.4342 - val_loss: 148.6057
Epoch 19/100
23/23 - 0s - 6ms/step - loss: 163.0195 - val_loss: 149.6037
Epoch 20/100
23/23 - 0s - 6ms/step - loss: 160.3451 - val_loss: 147.3689
Epoch 21/100
23/23 - 0s - 6ms/step - loss: 158.1639 - val_loss: 147.2744
Epoch 22/100
23/23 - 0s - 6ms/step - loss: 156.3458 - val_loss: 146.6831
Epoch 23/100
23/23 - 0s - 6ms/step - loss: 153.9270 - val_loss: 147.6725
Epoch 24/100
23/23 - 0s - 7ms/step - loss: 153.8987 - val_loss: 149.1527
Epoch 25/100
23/23 - 0s - 6ms/step - loss: 150.8270 - val_loss: 145.7485
Epoch 26/100
23/23 - 0s - 5ms/step - loss: 149.4830 - val_loss: 148.1973
Epoch 27/100
23/23 - 0s - 5ms/step - loss: 147.4507 - val_loss: 145.6387
Epoch 28/100
23/23 - 0s - 5ms/step - loss: 146.0167 - val_loss: 145.3526
Epoch 29/100
23/23 - 0s - 8ms/step - loss: 144.4591 - val_loss: 147.5372
Epoch 30/100
23/23 - 0s - 6ms/step - loss: 143.2558 - val_loss: 147.1967
Epoch 31/100
23/23 - 0s - 7ms/step - loss: 141.9057 - val_loss: 147.7552
Epoch 32/100
23/23 - 0s - 5ms/step - loss: 140.3518 - val_loss: 147.2177
Epoch 33/100
23/23 - 0s - 6ms/step - loss: 138.8950 - val_loss: 147.1696
Epoch 34/100
23/23 - 0s - 5ms/step - loss: 137.4182 - val_loss: 147.3637
Epoch 35/100
23/23 - 0s - 5ms/step - loss: 136.6256 - val_loss: 148.3323
Epoch 36/100
23/23 - 0s - 5ms/step - loss: 134.4858 - val_loss: 146.5432
Epoch 37/100
23/23 - 0s - 6ms/step - loss: 133.0213 - val_loss: 147.5959
Epoch 38/100
23/23 - 0s - 6ms/step - loss: 131.8708 - val_loss: 148.0699
Epoch 39/100
23/23 - 0s - 6ms/step - loss: 130.3913 - val_loss: 148.3845
Epoch 40/100
23/23 - 0s - 8ms/step - loss: 129.0976 - val_loss: 148.2109
Epoch 41/100
23/23 - 0s - 6ms/step - loss: 127.0881 - val_loss: 147.0340
Epoch 42/100
23/23 - 0s - 5ms/step - loss: 125.9325 - val_loss: 147.9421
Epoch 43/100
23/23 - 0s - 6ms/step - loss: 124.4927 - val_loss: 150.3867
Epoch 44/100
23/23 - 0s - 6ms/step - loss: 122.3201 - val_loss: 147.4209
Epoch 45/100
23/23 - 0s - 8ms/step - loss: 120.8827 - val_loss: 146.0632
Epoch 46/100
23/23 - 0s - 7ms/step - loss: 118.8333 - val_loss: 145.7180
Epoch 47/100
23/23 - 0s - 7ms/step - loss: 117.7957 - val_loss: 145.5027
Epoch 48/100
23/23 - 0s - 7ms/step - loss: 115.2522 - val_loss: 147.4821
Epoch 49/100
23/23 - 0s - 8ms/step - loss: 113.7233 - val_loss: 142.8213
Epoch 50/100
23/23 - 0s - 7ms/step - loss: 111.8386 - val_loss: 144.4714
Epoch 51/100
23/23 - 0s - 7ms/step - loss: 109.1066 - val_loss: 145.0059
Epoch 52/100
23/23 - 0s - 5ms/step - loss: 107.3701 - val_loss: 141.1181
Epoch 53/100
23/23 - 0s - 6ms/step - loss: 104.7405 - val_loss: 142.6879
Epoch 54/100
23/23 - 0s - 6ms/step - loss: 102.0342 - val_loss: 140.9082
Epoch 55/100
23/23 - 0s - 6ms/step - loss: 99.1034 - val_loss: 135.9464
Epoch 56/100
23/23 - 0s - 6ms/step - loss: 96.2836 - val_loss: 137.9878
Epoch 57/100
23/23 - 0s - 5ms/step - loss: 93.6783 - val_loss: 133.5663
Epoch 58/100
23/23 - 0s - 6ms/step - loss: 90.4387 - val_loss: 134.1148
Epoch 59/100
23/23 - 0s - 6ms/step - loss: 86.8080 - val_loss: 128.2768
Epoch 60/100
23/23 - 0s - 6ms/step - loss: 84.3107 - val_loss: 132.1234
Epoch 61/100
23/23 - 0s - 6ms/step - loss: 80.5715 - val_loss: 126.4744
Epoch 62/100
23/23 - 0s - 6ms/step - loss: 77.9570 - val_loss: 122.5293
Epoch 63/100
23/23 - 0s - 5ms/step - loss: 74.9282 - val_loss: 124.9307
Epoch 64/100
23/23 - 0s - 6ms/step - loss: 72.9543 - val_loss: 117.4563
Epoch 65/100
23/23 - 0s - 8ms/step - loss: 69.7383 - val_loss: 119.9019
Epoch 66/100
23/23 - 0s - 6ms/step - loss: 67.0262 - val_loss: 117.2493
Epoch 67/100
23/23 - 0s - 6ms/step - loss: 64.8810 - val_loss: 112.4683
Epoch 68/100
23/23 - 0s - 5ms/step - loss: 63.0107 - val_loss: 114.1742
Epoch 69/100
23/23 - 0s - 6ms/step - loss: 60.8376 - val_loss: 112.5327
Epoch 70/100
23/23 - 0s - 6ms/step - loss: 58.8583 - val_loss: 115.1259
Epoch 71/100
23/23 - 0s - 8ms/step - loss: 57.4900 - val_loss: 112.7042
Epoch 72/100
23/23 - 0s - 6ms/step - loss: 56.2193 - val_loss: 117.0672
Epoch 73/100
23/23 - 0s - 6ms/step - loss: 54.6931 - val_loss: 110.5900
Epoch 74/100
23/23 - 0s - 7ms/step - loss: 52.9029 - val_loss: 115.1123
Epoch 75/100
23/23 - 0s - 5ms/step - loss: 51.9928 - val_loss: 111.9655
Epoch 76/100
23/23 - 0s - 5ms/step - loss: 50.0364 - val_loss: 112.6254
Epoch 77/100
23/23 - 0s - 6ms/step - loss: 49.1185 - val_loss: 114.4887
Epoch 78/100
23/23 - 0s - 6ms/step - loss: 48.2737 - val_loss: 110.7731
Epoch 79/100
23/23 - 0s - 6ms/step - loss: 46.2618 - val_loss: 115.2056
Epoch 80/100
23/23 - 0s - 6ms/step - loss: 45.8927 - val_loss: 115.8106
Epoch 81/100
23/23 - 0s - 6ms/step - loss: 44.1536 - val_loss: 120.0238
Epoch 82/100
23/23 - 0s - 6ms/step - loss: 43.1678 - val_loss: 117.2085
Epoch 83/100
23/23 - 0s - 6ms/step - loss: 42.4715 - val_loss: 109.8107
Epoch 84/100
23/23 - 0s - 5ms/step - loss: 41.6550 - val_loss: 113.2512
Epoch 85/100
23/23 - 0s - 6ms/step - loss: 40.3668 - val_loss: 114.1594
Epoch 86/100
23/23 - 0s - 6ms/step - loss: 39.7232 - val_loss: 114.4258
Epoch 87/100
23/23 - 0s - 7ms/step - loss: 39.0364 - val_loss: 126.3300
Epoch 88/100
23/23 - 0s - 6ms/step - loss: 38.5765 - val_loss: 113.2372
Epoch 89/100
23/23 - 0s - 6ms/step - loss: 37.7932 - val_loss: 123.8567
Epoch 90/100
23/23 - 0s - 5ms/step - loss: 37.3573 - val_loss: 118.1937
Epoch 91/100
23/23 - 0s - 6ms/step - loss: 36.4926 - val_loss: 118.3868
Epoch 92/100
23/23 - 0s - 6ms/step - loss: 36.1689 - val_loss: 127.7208
Epoch 93/100
23/23 - 0s - 8ms/step - loss: 35.8616 - val_loss: 115.2606
Epoch 94/100
23/23 - 0s - 6ms/step - loss: 35.0414 - val_loss: 123.4121
Epoch 95/100
23/23 - 0s - 5ms/step - loss: 34.5372 - val_loss: 123.1255
Epoch 96/100
23/23 - 0s - 5ms/step - loss: 34.1410 - val_loss: 118.8262
Epoch 97/100
23/23 - 0s - 6ms/step - loss: 33.8016 - val_loss: 127.3065
Epoch 98/100
23/23 - 0s - 6ms/step - loss: 33.3967 - val_loss: 121.1483
Epoch 99/100
23/23 - 0s - 5ms/step - loss: 32.9149 - val_loss: 119.2160
Epoch 100/100
23/23 - 0s - 6ms/step - loss: 32.7193 - val_loss: 126.9731